import { NextResponse } from 'next/server';

const dictionary = {
  blog: 'بلاگ',
  summary: 'خلاصہ',
  content: 'مواد',
  article: 'مضمون',
  information: 'معلومات',
  read: 'پڑھنا',
  write: 'لکھنا',
  important: 'اہم',
  topic: 'موضوع',
  learn: 'سیکھنا',
  description: 'تفصیل',
  author: 'مصنف',
  published: 'شائع شدہ',
  update: 'تازہ کاری',
  review: 'جائزہ',
  tips: 'مشورے',
  guide: 'رہنما',
  tutorial: 'سبق',
  experience: 'تجربہ',
  idea: 'خیال',
  explore: 'دریافت کرنا',
  discover: 'کھوجنا',
  latest: 'تازہ ترین',
  popular: 'مقبول',
  useful: 'مفید',
  feature: 'خصوصیت',
  introduction: 'تعارف',
  conclusion: 'نتیجہ',
  opinion: 'رائے',
  feedback: 'رائے',
  improve: 'بہتر بنانا',
  analysis: 'تجزیہ',
  resource: 'وسیلہ',
  perspective: 'نقطہ نظر',
  highlight: 'اہم بات',
  example: 'مثال',
  benefit: 'فائدہ',
  advantage: 'برتری',
  disadvantage: 'نقصان',
  problem: 'مسئلہ',
  solution: 'حل',
  question: 'سوال',
  answer: 'جواب',
  comment: 'تبصرہ',
  share: 'بانٹنا',
  readMore: 'مزید پڑھیں',
  subscribe: 'سبسکرائب کریں',
  hair: 'بال',
  growth: 'بڑھوتری',
  food: 'کھانا',
  protein: 'پروٹین',
  vitamin: 'وٹامن',
  health: 'صحت',
    mother: 'ماں',
  father: 'باپ',
  sister: 'بہن',
  brother: 'بھائی',
  home: 'گھر',
  kitchen: 'باورچی خانہ',
  room: 'کمرہ',
  bed: 'بستر',
  window: 'کھڑکی',
  garden: 'باغ',
  street: 'گلی',
  market: 'بازار',
  shop: 'دکان',
  job: 'نوکری',
  office: 'دفتر',
  hospital: 'ہسپتال',
  doctor: 'ڈاکٹر',
  teacher: 'استاد',
  student: 'طالب علم',
  baby: 'بچہ',
  morning: 'صبح',
  evening: 'شام',
  week: 'ہفتہ',
  month: 'مہینہ',
  year: 'سال',
  sky: 'آسمان',
  cloud: 'بادل',
  rain: 'بارش',
  wind: 'ہوا',
  fire: 'آگ',
  earth: 'زمین',
  flower: 'پھول',
  bird: 'پرندہ',
  dog: 'کتا',
  cat: 'بلی',
  fruit: 'پھل',
  vegetable: 'سبزی',
  bread: 'روٹی',
  milk: 'دودھ',
  tea: 'چائے',
  coffee: 'کافی',
  sugar: 'شکر',
  salt: 'نمک',
  pain: 'درد',
  happiness: 'خوشی',
  fear: 'خوف',
  anger: 'غصہ',
  peace: 'امن',
  war: 'جنگ',
  game: 'کھیل',
  music: 'موسیقی',
  art: 'فن',
  eggs: 'انڈے',
  nuts: 'مغز',
  fish: 'مچھلی',
  omega: 'اومیگا',
  scalp: 'سر کی کھال',
  summary: 'خلاصہ',
  and: 'اور',
  is: 'ہے',
  for: 'کے لیے',
  the: 'یہ',
  are: 'ہیں',
  helps: 'مدد کرتا ہے',
  important: 'اہم',
  prevent: 'روکنا',
  loss: 'نقصان',
  damage: 'نقصان',
  rich: 'مالا مال',
  in: 'میں',
  found: 'ملا',
  contains: 'شامل ہے',
  improves: 'بہتر بناتا ہے',
  blood: 'خون',
  circulation: 'گردش',
  roots: 'جڑیں',
  beneficial: 'فائدہ مند',
  strong: 'مضبوط',
  shine: 'چمک',
  dry: 'خشک',
  oily: 'چکنا',
  preventing: 'روک تھام',
  breakage: 'ٹوٹ پھوٹ',
  natural: 'قدرتی',
  remedy: 'علاج',
  condition: 'حالت',
  growths: 'نشوونما',
  daily: 'روزانہ',
  intake: 'خوراک',
  source: 'ذریعہ',
  diet: 'خوراک',
  essential: 'ضروری',
  care: 'نگہداشت',
  maintain: 'برقرار رکھنا',
  follicles: 'بالوں کی جڑیں',
  hydration: 'نمی',
  repair: 'مرمت',
  cells: 'خلیے',
  reduce: 'کم کریں',
  stress: 'تناؤ',
  promote: 'فروغ دینا',
  water: 'پانی',
  house: 'گھر',
  car: 'گاڑی',
  book: 'کتاب',
  time: 'وقت',
  day: 'دن',
  night: 'رات',
  family: 'خاندان',
  friend: 'دوست',
  child: 'بچہ',
  school: 'سکول',
  work: 'کام',
  life: 'زندگی',
  love: 'محبت',
  money: 'پیسہ',
  city: 'شہر',
  tree: 'درخت',
  sun: 'سورج',
  moon: 'چاند',
  road: 'سڑک',
  heart: 'دل',
  mind: 'دماغ',
  hand: 'ہاتھ',
  eye: 'آنکھ',
  door: 'دروازہ',
  table: 'میز',
  chair: 'کرسی',
  phone: 'فون',
  computer: 'کمپیوٹر',
  world: 'دنیا',
  dream: 'خواب',
  hope: 'امید',
  problem: 'مسئلہ',
  solution: 'حل',
  question: 'سوال',
  answer: 'جواب',
  place: 'جگہ',
  person: 'شخص',
  idea: 'خیال',
  light: 'روشنی',

  // Verbs (Actions, States)
  eat: 'کھانا',
  drink: 'پینا',
  sleep: 'سونے',
  run: 'دوڑنا',
  walk: 'چلنا',
  speak: 'بولنا',
  listen: 'سننا',
  see: 'دیکھنا',
  feel: 'محسوس کرنا',
  think: 'سوچنا',
  go: 'جانا',
  come: 'آنا',
  give: 'دینا',
  take: 'لینا',
  make: 'بنانا',
  know: 'جاننا',
  learn: 'سیکھنا',
  teach: 'سکھانا',
  write: 'لکھنا',
  read: 'پڑھنا',
  buy: 'خریدنا',
  sell: 'بیچنا',
  open: 'کھولنا',
  close: 'بند کرنا',
  start: 'شروع کرنا',
  stop: 'روکنا',
  become: 'بننا',
  seem: 'لگنا',
  help: 'مدد کرنا',
  try: 'کوشش کرنا',
  understand: 'سمجھنا',
  change: 'بدلنا',
  wait: 'انتظار کرنا',
  sit: 'بیٹھنا',
  stand: 'کھڑا ہونا',
  lie: 'لیٹنا',
  jump: 'چھلانگ لگانا',
  sing: 'گانا',
  dance: 'ناچنا',
  laugh: 'ہنسنا',
  cry: 'رونا',
  smile: 'مسکراہٹ',
  shout: 'چلانا',
  watch: 'دیکھنا',
  touch: 'چھونا',
  hold: 'پکڑنا',
  push: 'دھکیلنا',
  pull: 'کھینچنا',
  find: 'ڈھونڈنا',
  lose: 'کھونا',
  win: 'جیتنا',
  play: 'کھیلنا',
  study: 'پڑھائی کرنا',
  works: 'کام کرنا',
  rest: 'آرام کرنا',
  travel: 'سفر کرنا',
  meet: 'ملنا',
  call: 'بلانا',
  ask: 'پوچھنا',
  tell: 'بتانا',
  show: 'دکھانا',
  follow: 'پیچھا کرنا',
  decide: 'فیصلہ کرنا',
  believe: 'یقین کرنا',
  forget: 'بھولنا',
  remember: 'یاد کرنا',
  grow: 'بڑھنا',
  break: 'توڑنا',
  build: 'بنانا',
  carry: 'اٹھانا',

  // Pronouns
  I: 'میں',
  you: 'تم',
  he: 'وہ (مرد)',
  she: 'وہ (عورت)',
  it: 'یہ',
  we: 'ہم',
  they: 'وہ (جمع)',
  me: 'مجھے',
  him: 'اسے (مرد)',
  her: 'اسے (عورت)',
  us: 'ہمیں',
  them: 'انہیں',
  my: 'میرا',
  your: 'تمہارا',
  his: 'اس کا (مرد)',
  its: 'اس کا',
  our: 'ہمارا',
  their: 'ان کا',
  mine: 'میرا',
  yours: 'تمہارا',
  hers: 'اس کا (عورت)',
  ours: 'ہمارا',
  theirs: 'ان کا',
  myself: 'خود',
  yourself: 'اپنے آپ',
  himself: 'خود (مرد)',
  herself: 'خود (عورت)',
  itself: 'خود',
  ourselves: 'ہم خود',
  themselves: 'خود',

  // Adjectives (Descriptive)
  good: 'اچھا',
  bad: 'برا',
  big: 'بڑا',
  small: 'چھوٹا',
  hot: 'گرم',
  cold: 'ٹھنڈا',
  happy: 'خوش',
  sad: 'اداس',
  beautiful: 'خوبصورت',
  ugly: 'بدصورت',
  fast: 'تیز',
  slow: 'آہستہ',
  easy: 'آسان',
  hard: 'مشکل',
  new: 'نیا',
  old: 'پرانا',
  young: 'جوان',
  long: 'لمبا',
  short: 'چھوٹا',
  clean: 'صاف',
  dirty: 'گندا',
  safe: 'محفوظ',
  dangerous: 'خطرناک',
  kind: 'مہربان',
  cruel: 'ظالم',
  bright: 'روشن',
  dark: 'اندھیرا',
  soft: 'نرم',
  heavy: 'بھاری',
  light: 'ہلکا',
  warm: 'گرم',
  cool: 'ٹھنڈا',
  pretty: 'خوبصورت',
  weak: 'کمزور',
  tall: 'لمبا',
  healthy: 'صحت مند',
  sick: 'بیمار',
  busy: 'مصروف',
  free: 'آزاد',
  expensive: 'مہنگا',
  cheap: 'سستا',

  // Adverbs (Modify Verbs, Adjectives, etc.)
  quickly: 'تیزی سے',
  slowly: 'آہستہ',
  well: 'اچھی طرح',
  badly: 'بری طرح',
  always: 'ہمیشہ',
  never: 'کبھی نہیں',
  often: 'اکثر',
  sometimes: 'کبھی کبھار',
  now: 'اب',
  then: 'تب',
  here: 'یہاں',
  there: 'وہاں',
  today: 'آج',
  tomorrow: 'کل',
  yesterday: 'کل (گزرا ہوا)',
  easily: 'آسانی سے',
  carefully: 'احتیاط سے',
   soon: 'جلد',
  late: 'دیر سے',
  early: 'جلدی',
  happily: 'خوشی سے',
  sadly: 'اداسی سے',
  quietly: 'خاموشی سے',
  loudly: 'بلند آواز سے',
  clearly: 'واضح طور پر',
  suddenly: 'اچانک',
  almost: 'تقریباً',
  too: 'بہت',
  very: 'بہت',
  enough: 'کافی',
  hardly: 'مشکل سے',
  completely: 'مکمل طور پر',
  partly: 'جزوی طور پر',

  // Prepositions
  at: 'پر',
  on: 'پر',
  with: 'کے ساتھ',
  from: 'سے',
  to: 'کی طرف',
  by: 'کے ذریعے',
  about: 'کے بارے میں',
  under: 'نیچے',
  over: 'اوپر',
  between: 'کے درمیان',
  behind: 'پیچھے',
  above: 'اوپر',
  below: 'نیچے',
  inside: 'اندر',
  outside: 'باہر',
  near: 'قریب',
  far: 'دور',
  through: 'کے ذریعے',
  across: 'پار',
  along: 'ساتھ',
  toward: 'کی طرف',
  against: 'کے خلاف',

  // Conjunctions
  but: 'لیکن',
  or: 'یا',
  because: 'کیونکہ',
  if: 'اگر',
  when: 'جب',
  although: 'حالانکہ',
  while: 'جبکہ',
  so: 'تو',
  yet: 'پھر بھی',
  nor: 'اور نہ',
  since: 'کیونکہ',
  until: 'تک',
  unless: 'جب تک کہ',
  as: 'جیسے',

  // Interjections
  oh: 'اوہ',
  wow: 'واہ',
  ouch: 'اوچ',
  hey: 'ہائے',
  alas: 'ہائے',
  hurrah: 'ہرے',
  oops: 'اوہو',
  bravo: 'واہ',
  hush: 'خاموش',
  yay: 'یے',

  // Articles/Determiners
  a: 'ایک',
  an: 'ایک',
  some: 'کچھ',
  any: 'کوئی',
  this: 'یہ',
  that: 'وہ',
  these: 'یہ (جمع)',
  those: 'وہ (جمع)',
  every: 'ہر',
  each: 'ہر ایک',
  all: 'سب',
  few: 'چند',
  many: 'بہت سے',
  more: 'زیادہ',
  most: 'سب سے زیادہ',
  both: 'دونوں',
  either: 'کوئی ایک',
  neither: 'کوئی بھی نہیں',
  several: 'کئی',
  'at least': 'کم از کم',
  another: 'ایک اور',
  such: 'ایسا',
  what: 'کیا',
  which: 'کون سا',
  whose: 'کس کا',


  // Modal Verbs (Auxiliary)
  should: 'چاہیے',
  can: 'کر سکتے ہیں',
  will: 'کریں گے',
  would: 'کریں گے (مشروط)',
  must: 'لازمی',
  may: 'شاید',
  might: 'شاید (امکان)',
  shall: 'کریں گے',
  could: 'کر سکتے تھے',
  'ought to': 'چاہیے',
  need: 'ضرورت',
  best: 'بہترین',
  foods: 'خوراکیں',
  high: 'زیادہ',
  nutritional: 'غذائیت سے بھرپور',
  value: 'قدر',
  like: 'جیسے',
  leafy: 'پتوں والی',
  green: 'سبز',
  of: 'کا'
};


export async function POST(request) {
  try {
    const { text } = await request.json();
    if (!text) {
      return NextResponse.json({ error: 'Text is required' }, { status: 400 });
    }

    const translated = text
      .split(' ')
      .map(word => dictionary[word.toLowerCase()] || word)
      .join(' ');

    return NextResponse.json({ translated });
  } catch (error) {
    return NextResponse.json({ error: 'Failed to translate text' }, { status: 500 });
  }
}